DROP SCHEMA IF EXISTS RMT;

CREATE SCHEMA RMT;

DROP TABLE IF EXISTS RMT.MT_CLIENT;

CREATE TABLE RMT.MT_CLIENT (
CLIENT_ID LONG PRIMARY KEY NOT NULL,
CLIENT_FIRST_NAME VARCHAR(30),
CLIENT_LAST_NAME VARCHAR(30),
CREATED_DATE TIMESTAMP NOT NULL,
CREATED_USER VARCHAR(30) NOT NULL,
UPDATED_DATE TIMESTAMP NOT NULL,
UPDATED_USER VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX RMT.IDX_MT_CLIENT_1 on RMT.MT_CLIENT(CLIENT_ID);

DROP TABLE IF EXISTS RMT.MT_ACCOUNT;

CREATE TABLE RMT.MT_ACCOUNT (
ACCOUNT_ID LONG PRIMARY KEY NOT NULL,
CLIENT_ID LONG NOT NULL,
ACCOUNT_BALANCE DECIMAL(19,4),
ACCOUNT_CURRENCY_CODE VARCHAR(3),
CREATED_DATE TIMESTAMP NOT NULL,
CREATED_USER VARCHAR(30) NOT NULL,
UPDATED_DATE TIMESTAMP NOT NULL,
UPDATED_USER VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX RMT.IDX_MT_ACCOUNT_1 on RMT.MT_ACCOUNT(ACCOUNT_ID);

DROP TABLE IF EXISTS RMT.MT_CURRENCY;

CREATE TABLE RMT.MT_CURRENCY (
CURRENCY_CODE VARCHAR(3) PRIMARY KEY NOT NULL,
CURRENCY_NAME VARCHAR(30),
CURRENCY_COUNTRY VARCHAR(30),
CURRENCY_ACTIVE CHAR(1) NOT NULL,
CREATED_DATE TIMESTAMP NOT NULL,
CREATED_USER VARCHAR(30) NOT NULL,
UPDATED_DATE TIMESTAMP NOT NULL,
UPDATED_USER VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX RMT.IDX_MT_CURRENCY_1 ON RMT.MT_CURRENCY(CURRENCY_CODE);
CREATE INDEX RMT.IDX_MT_CURRENCY_2 ON RMT.MT_CURRENCY(CURRENCY_CODE, CURRENCY_ACTIVE);

DROP SEQUENCE IF EXISTS RMT.MT_ACCOUNT_SEQ;

CREATE SEQUENCE RMT.MT_ACCOUNT_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
DROP TABLE IF EXISTS RMT.MT_TRANSACTION;

CREATE TABLE RMT.MT_TRANSACTION (
TRANSACTION_ID LONG PRIMARY KEY NOT NULL,
SOURCE_ACCOUNT_ID LONG NOT NULL,
DESTINATION_ACCOUNT_ID LONG NOT NULL,
AMOUNT DECIMAL(19,4),
ACCOUNT_CURRENCY_CODE VARCHAR(3),
COMMENT VARCHAR(100) NOT NULL,
STATUS VARCHAR(10) NOT NULL,
CREATED_DATE TIMESTAMP NOT NULL,
CREATED_USER VARCHAR(30) NOT NULL,
UPDATED_DATE TIMESTAMP NOT NULL,
UPDATED_USER VARCHAR(30) NOT NULL
);

CREATE UNIQUE INDEX RMT.IDX_MT_TRANSACTION_1 on RMT.MT_TRANSACTION(TRANSACTION_ID);

DROP SEQUENCE IF EXISTS RMT.MT_TRANSACTION_SEQ;

CREATE SEQUENCE RMT.MT_TRANSACTION_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;